services:
  - type: web
    name: erpcrm
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn erpcrm.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: erpcrm.settings
      - key: PYTHON_VERSION
        value: 3.12.1
