# Generated by Django 5.2 on 2025-04-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(blank=True, choices=[('PT', 'Producto terminado'), ('MP', 'Materia prima'), ('SV', 'Servicio')], max_length=2, null=True),
        ),
    ]
