# Generated by Django 5.2 on 2025-04-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_producto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='clasificacion',
            field=models.CharField(blank=True, help_text='Ej. A, B, C, etc.', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
