# Generated by Django 5.2 on 2025-04-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0003_producto_clasificacion_producto_stock_minimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(blank=True, choices=[('PT', 'Producto Terminado'), ('MP', 'Materia Prima'), ('SV', 'Servicio')], max_length=2, null=True),
        ),
    ]
