# Generated by Django 5.2 on 2025-04-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0005_categoriaproducto_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
